#---------------------------------#
#       restore nuget packages    #
#---------------------------------#
before_build:
  - nuget restore
  
#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# to add several platforms to build matrix:
#platform:
#  - x86
#  - Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# to add several configurations to build matrix:
#configuration:
#  - Debug
#  - Release

build:
  parallel: true                  # enable MSBuild parallel builds
  project: TestApp.csproj         # path to Visual Studio solution or project

  # MSBuild verbosity level
  verbosity: normal # quiet|minimal|normal|detailed

#---------------------------------#
#      after build - create zip   #
#---------------------------------#

after_build:
  7z a myapp.zip %APPVEYOR_BUILD_FOLDER%\bin\$(configuration)\*.*

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path:  myapp.zip  # bin\$(configuration)\*.*
    name: myapp

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:
  - provider: GitHub
    auth_token:
      secure: NmzVA2Q8U/9yrMsRm6nESEP5e3/edoT7DYHCWPdOG2uH9zVzZDC9z2Bc6FLotpVB # your encrypted token from GitHub
    artifact: /.*\.*/           # upload all NuGet packages to release assets
    draft: false
    prerelease: false
    on:
      branch: master                # release from master branch only
      #appveyor_repo_tag: true       # deploy on tag push only
