#---------------------------------#
#       restore nuget packages    #
#---------------------------------#
before_build:
  - nuget restore
  
#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# to add several platforms to build matrix:
#platform:
#  - x86
#  - Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# to add several configurations to build matrix:
#configuration:
#  - Debug
#  - Release

build:
  parallel: true                  # enable MSBuild parallel builds
  project: TestApp.csproj         # path to Visual Studio solution or project

  # MSBuild verbosity level
  verbosity: normal # quiet|minimal|normal|detailed

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  # pushing a single file with environment variable in path and "Deployment name" specified
  - path: bin\$(configuration)\*.*
    name: myapp

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:
  - provider: GitHub
    auth_token:
      secure: <your encrypted token> # your encrypted token from GitHub
    artifact: /.*\.*/           # upload all NuGet packages to release assets
    draft: false
    prerelease: false
    on:
      branch: master                # release from master branch only
      #appveyor_repo_tag: true       # deploy on tag push only
